config/routes.rb
Rails.application.routes.draw do
  resources :claims
  resources :bids
  devise_for :users
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'
  resources :products
  resources :products do
    member do
      get :details
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/claim.rb
class Claim < ApplicationRecord
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :set_claim, only: [:show, :edit, :update, :destroy]

  #index function:
  #gets a list of all the products claimed
  #conditions of claim display are put in erb in the view {eg. only claims by curr user will be displayed, etc.}
  # Requests: GET
  def index
    @claims = Claim.all
  end

  #show function:
  #functionality : to view the claim details after it is claimed
  def show
  end

  #creates new claim as and when the highest bidder decides to claim item 
  def new
    @claim = Claim.new
    @user=current_user
    @bid =  Bid.find(params[:bid_id])
  end

  # GET /claims/1/edit
  def edit
  end

  #called when submit claim button pushed
  #details stored in model
  #once claimed, product's claimed value becomes true and is not displayed to new buyers anymore
  #upon claiming, user_id is stored in model
  def create
    @claim = Claim.new(claim_params)
    @user=User.find(@claim.user_id)
    @product=Product.find(@claim.c_product_id)
    @product.cuser_id=@claim.user_id
    @product.save
    @product.claimed=true
    @product.save
    respond_to do |format|
      if @claim.save
        format.html { redirect_to @claim, notice: 'Claim was successfully created.' }
        format.json { render :show, status: :created, location: @claim }
      else
        format.html { render :new }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  #called when update claim button pushed
  #details stored in model
  def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to @claim, notice: 'Claim was successfully updated.' }
        format.json { render :show, status: :ok, location: @claim }
      else
        format.html { render :edit }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  #pretty much useless, but available if needed
  #not used, because it doesn't make sense to delete a claim after the seller is assured that transaction is done
  def destroy
    @claim.destroy
    respond_to do |format|
      format.html { redirect_to claims_url, notice: 'Claim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim
      @claim = Claim.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def claim_params
      params.require(:claim).permit(:c_product_id, :c_product_name, :c_bid_forproduct, :integer, :user_id)
    end
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/views/claims/_form.html.erb
<%= form_with(model: claim, local: true) do |form| %>
  <% if claim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(claim.errors.count, "error") %> prohibited this claim from being saved:</h2>

      <ul>
        <% claim.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div style="width:400px; margin:0 auto;", class="form">
    <div class="field1">
      <%= form.label :product_id %>
      <%= form.text_field :c_product_id, :value=>@bid.product_id, :readonly=>true, :class=>"field" %>
    </div>

    <div class="field1">
      <%= form.label :product_name %>
      <%= form.text_field :c_product_name, :value=>@bid.product_name, :readonly=>true, :class=>"field"  %>
    </div>

    <div class="field1">
      <%= form.label :bid_for_product %>
      <%= form.text_field :c_bid_forproduct, :value=>@bid.bid_value, :readonly=>true, :class=>"field"  %>
    </div>

    <div class="field1">
      <%= form.label :user_id %>
      <%= form.text_field :user_id, :value=>current_user.id, :readonly=>true, :class=>"field"  %>
    </div>

    <div class="actions">
      <%= form.submit "Claim Item Now" %>
    </div>
  </div>

<% end %>

app/views/claims/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="header">Claims</h1>

<table id="customers">
  <thead>
    <tr>
      <th>Product_ID</th>
      <th>Product_Name</th>
      <th>Bid_Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @claims.each do |claim| %>
      <%#next line checks if current user is the one who has claimed the product or not, if yes then display, else move on%>
      <%if claim.user_id==current_user.id%>
        <tr>
          <td><%= claim.c_product_id %></td>
          <td><%= claim.c_product_name %></td>
          <td><%= claim.c_bid_forproduct %></td>
          <td><%= link_to 'Show', claim %></td>
        </tr>
      <% end %>  
    <% end %>
  </tbody>
</table>

<br>

app/views/claims/new.html.erb
<h1 id="header">Claim Product<br><h3 id="header">Kindly Verify Details</h3></h1>

<%= render 'form', claim: @claim %>

<%= link_to 'Back', claims_path %>

app/views/claims/show.html.erb
<p id="notice"><%= notice %></p>
<h1 id="header">Claim Successful!</h1>
<div class="show">
  <p class="list_info">
    <strong>Product ID : </strong>
    <%= @claim.c_product_id %>
  </p>

  <p class="list_info">
    <strong>Product Name : </strong>
    <%= @claim.c_product_name %>
  </p>

  <p class="list_info">
    <strong>Bid Value : </strong>
    <%= @claim.c_bid_forproduct %>
  </p>

  <p class="list_info">
    <strong>User ID : </strong>
    <%= @claim.user_id %>
  </p>


<%= link_to 'Back', claims_path %>