config/routes.rb
Rails.application.routes.draw do
  resources :claims
  resources :bids
  devise_for :users
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'
  resources :products
  resources :products do
    member do
      get :details
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bid.rb
class Bid < ApplicationRecord
    belongs_to :product, optional: true
    #basic table inheritance
end

app/controllers/bids_controller.rb
require "product"
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]

  #index function:
  #gets a list of all the bids placed
  #conditions of bid display are put in erb in the view {eg. only bids placed by curr user will be displayed, etc.}
  # Requests: GET
  def index
    @bids = Bid.all
  end

  #show function:
  #functionality : to view the bid details after it is placed
  def show
    @bid = Bid.find(params[:id]) 
    @product=Product.find(@bid.product_id)
  end

  #creates a new bid for given product on sale
  #again, conditions put in the view as erb
  def new  
    @product =  Product.find(params[:product_id])    
    @bid = Bid.new 
  end 

  def product_name
    @product=product.name
  end  

  def product_id
    @product=product.id
  end

  
  #editing a bid after it is placed
  def edit
  
  end

  #called when submit bid button pushed
  #details stored in model
  def create
    @bid = Bid.new(bid_params)
    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid, notice: 'Bid was successfully created.' }
        format.json { render :show, status: :created, location: @bid }
      else
        format.html { render :new }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  #called when update bid button pushed
  #details updated in model
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  #called when delete bid button pushed
  #details removed from model
  def destroy
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to bids_url, notice: 'Bid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bid_params
      params.require(:bid).permit(:user_email, :bid_value, :product_id, :product_name, :product_deadline)
    end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_form.html.erb
<%= form_with(model: bid, local: true) do |form| %>

  <% if bid.errors.any? %>

    <div id="error_explanation">
    
      <h2><%= pluralize(bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      
        <% bid.errors.full_messages.each do |message| %>
        
          <li><%= message %></li>
        
        <% end %>
      
      </ul>
    
    </div>
  <% end %>
  
  <div style="width:400px; margin:0 auto;", class="form">
  
    <div class="field1" >
      <%= form.label :user_email %>
      <%= form.text_field :user_email, :value => current_user.email, :readonly=>true, :class=>"field"   %>
    </div>

    <div class="field1">
      <%= form.label :bid_value %>
      <%= form.text_field :bid_value, :class=>"field"  %>
    </div>
  
    <div class="field1h" style="visibility: hidden">
      <%= form.label :product_id %>
      <%= form.text_field :product_id ,:value => @product.id, :readonly => true%>
    </div>
  
    <div class="field1h" style="visibility: hidden">
      <%= form.label :product_name %>
      <%= form.text_field :product_name ,:value => @product.name, :readonly => true%>
    </div>  

    <div class="field1h" style="visibility: hidden">
      <%= form.label :deadline %>
      <%= form.date_select :product_deadline,:selected => @product.deadline  %>
    </div>

    <%#testing line%>
    
    <%params={:product_id=>product.id}%>

    <div class="field1">
      <%= form.submit "Place your bid"%>
    </div>
  
  </div>

<% end %>

app/views/bids/_form_edit.html.erb
<%= form_with(model: bid, local: true) do |form| %>
    <% if bid.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(bid.errors.count, "error") %> prohibited this bid from being saved:</h2>
  
        <ul>
          <% bid.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field">
      <%= form.label :user_email %>
      <%= form.text_field :user_email %>
    </div>
  
    <div class="field">
      <%= form.label :bid_value %>
      <%= form.text_field :bid_value %>
    </div>
    
      
  
     
    
  
    <div class="actions">
      <%= form.submit %>
    </div>
    <%end%>

app/views/bids/edit.html.erb
<h1 id="header">Editing Bid</h1>

<%= render 'form_edit', bid: @bid %>

<%= link_to 'Show', @bid %> |

<%= link_to 'Back', bids_path %>

app/views/bids/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="header">Bids</h1>

<table id="customers">
  <thead>
    <tr>
      <th>Bidder</th>
      <th>Bid</th>
      <th>Product</th>
      <th>Deadline</th>
      <th colspan="5"></th>
    </tr>
  </thead>

<%#displaying all the currently relevant bids%>
  
  <tbody>
    <% @bids.each do |bid| %>
      <%#the below line checks if the product exists, then display bids of that product BY CURRENT USER%>
      <%if bid.user_email==current_user.email && Product.exists?(id: bid.product_id) %>
        <tr class="bid_row">
          <td><%= bid.user_email %></td>
          <td><%= bid.bid_value %></td>
          <td><%=bid.product_name%></td>
          <td><%=bid.product_deadline%></td>
          <td><%= link_to 'Show Bid', bid %></td>
          <td><%= link_to 'Delete Bid', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <%end%>
      <%#otherwise delete that bid if product doesn't exist or it has been claimed%>
      <%if (!Product.exists?(id: bid.product_id))||(Product.where(claimed:true).exists?(id: bid.product_id)) %>
        <%bid.delete%>
      <%end%>  
    <% end %>
  </tbody>
</table>

<br>

<div id="link"></div>

app/views/bids/new.html.erb
<p><h1 id="header">YOU ARE BIDDING FOR</h1></p>
<div class="card">
  <p>
    <%= image_tag @product.image , class: "image_display"%>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= truncate(@product.description, :length => 80) %>
  </p>

  <p>
    <strong>Starting bid:</strong>
    <%= number_to_currency(@product.starting_bid) %>
  </p>

  <p>
    <strong>Deadline:</strong>
    <%= @product.deadline %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= @product.contact %>
  </p>
</div>

<%= render 'form', bid: @bid, product: @product %> 

<%= link_to 'Back', bids_path %>

app/views/bids/show.html.erb
<%#basic page to display Bid Details on creation or review%>
<p id="notice"><%= notice %></p>
<h1 id="header">Bid Successful!</h1>
<div class="show">
  <p class="list_info">
    <strong>User email : </strong>
    <%= @bid.user_email %>
  </p>

  <p class="list_info">
    <strong>Bid value : </strong>
    <%= @bid.bid_value %>
  </p>

  <p class="list_info">
    <strong>Product ID : </strong>
    <%= @bid.product_id %>
  </p>
  <p class="list_info">
    <strong>Product Name : </strong>
    <%= @bid.product_name %>
  </p>
</div>  
<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>